### ISSUE TITLE
Switch to a better supported CSS component library

### ISSUE THREAD

**Issue by xeonneon** [beer-garden/functionary#201]
In an effort to move away from Bulma due to a lack of new features and extensibility, we should switch which CSS component library we use. We should migrate to a component library that allows for extensibility so the Functionary UI has some personality to it, and ideally comes with accessibility features, such as focus trapping, out of the box.

**Comment by xeonneon** [comment]
I'm strongly in favor of a component library that is built on top of Tailwind CSS.

Some example component libraries include:
- [Tailwind Elements](https://tailwind-elements.com/)
- [DaisyUI](https://daisyui.com/)
  - Missing accessibility features
- [Tailwind UI Kit](https://tailwinduikit.com/components)
  - Missing accessibility features

**Comment by scott-taubman** [comment]
Current design thoughts based on recent discussions:

* Just use the default bootstrap colors for now.  We'll figure out a better / more compliant color scheme later
* The [bootstrap sidebar example](https://getbootstrap.com/docs/5.0/examples/sidebars/) basically looks like what I believe we want.
* Let's get rid of the top bar now so that the side bar looks good and we don't have to worry about picking a good complimentary color for the top bar.
