### ISSUE TITLE
Package Create overwrites/appends to existing files

### ISSUE THREAD

**Issue by kvig** [beer-garden/functionary#64]
I mixed up my commands and ran `functionary package create -l python kitchen_sink` when I already had a kitchen_sink directory. The create command overwrote my `functions.py` and appended a new yaml to the end of `package.yaml`. The command should be consistent in what it does, and either prompt to overwrite or fail and force the command to run again with a `-f` flag to overwrite what's there.

**Comment by scott-taubman** [comment]
I think have a `-f` to force the overwrite seems sensible, but I also kind of wonder what's the use case for when you'd use that?  And what's the expected behavior?  Does it wipe everything in the directory and then start you totally fresh?  Or does it leave any additional files you've added and just overwrite the ones that it would normally write (functions.py, package.yaml, etc.)?

I could also see taking the easy way out and just refusing to do anything if the directory isn't empty.  How would people feel about that?

**Comment by catattack05** [comment]
I think it's also worth noting that it would be good to decide what the behavior should be if the files in your directory are say in python, but you run the create command again and declare the package is now in javascript. Current behavior is that a new functions.js file will be created and the package.yaml will be overwritten with the new language, but the functions.py file will remain. As it stands now, files that are not function.py/js and package.yaml are not overwritten.

Not doing anything to the directory if it already exists and isn't empty would definitely be the easiest solution. Otherwise I would be inclined to leave it as package.yaml and functions.py/js get overwritten if the user uses -f and everything else remains

**Comment by catattack05** [comment]
In discussion, Scott and I have decided to go with his suggestion of just not doing anything when the dictionary isn't empty for right now
