### ISSUE TITLE
Provide more specific feedback / output when receiving error responses from the API

### ISSUE THREAD

**Issue by kvig** [beer-garden/functionary#66]
It would be useful to have a verbose command line option to commands to get a little more detail. I was trying to publish a package and the answer to what was wrong was in the return from the server. I would like to be able to specify `-v` to get the error output from the server.

**Comment by scott-taubman** [comment]
I think there still might be a case for a verbose option that just shows the full server response, but there's a more basic problem here in that the bare minimum information that should be displayed in the case of an error is not.  Sometimes the straight up wrong message is shown instead.

An easy to replicate example is the `package publish` command.  If the package.yaml fails validation, the error that the CLI displays should say as much and provide the validation error message so that the user knows how to fix it.  Instead, the error that gets displayed is:

```
Error: Please set an active environment id using 'environment set'
```

This would seem to indicate that the error handling is overly broad and makes bad assumptions about what a 400 error means.  I'm going to guess we knew this when we wrote the original version of the code, with the idea that we would circle back and improve the error handling.  I think that time to circle back is now, otherwise we're going to waste cycles troubleshooting basic errors as we use the CLI.

**Comment by catattack05** [comment]
My idea for how to start here to essentially to create another function to handle the errors within client.py's post request since at this point we'll probably be doing enough work specifically on error handling to justify it. The three errors I have so far thought of (that aren't handled somewhere else in the code) would be caused by having no environment_id set at all, having an invalid environment_id, and the invalid_package.yaml error that shows up in publishing. We should be able to tell what category the error is via the text of the response object generated. My initial thought would be if we don't have a better error message to display to the user in a click exception, to just pass the text of the response into the click exception.
